spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            # 初始化大小，最小，最大
            initial-size: 1
            min-idle: 3
            max-active: 20
            # 配置获取连接等待超时的时间
            max-wait: 6000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            time-between-eviction-runs-millis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            min-evictable-idle-time-millis: 30000
            reset-stat-enable: true
            test-on-borrow: false
            test-on-return: false
            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
    # 404交给异常处理器处理
    mvc:
        throw-exception-if-no-handler-found: true
    # 404交给异常处理器处理
    resources:
        add-mappings: false
mybatis:
    mapper-locations: classpath:mapping/*.xml
server:
    port: 8090
logging:
    # Debug打印SQL
    level:
        com.example.shirodemo.dao: debug